name: CI/CD - Deploy to Production

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  test:
    name: Run Test Cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js (or your runtime)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Or the command to run your test suite

  deploy:
    name: Deploy to Production
    needs: test  # Wait for tests to pass
    runs-on: ubuntu-latest

    if: success()  # Only deploy if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Production Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd /var/www/your-app
            git pull origin main
            npm install
            pm2 restart your-app-name
          EOF
